# Generated by Django 3.2.5 on 2021-08-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='topic',
            new_name='webpage',
        ),
    ]
